### ISSUE TITLE
Taskbar viewlet

### ISSUE THREAD

**Issue by seanupton** [upiq/uu.task#13]
We want to have a viewlet in the plone.abovecontentbody manager (Plone 4, not sure where is appropriate for this in Plone 5?).  This viewlet will display when task is due, who it is assigned to, and its status (note: this status may be different than the primary workflow state of the item, even if the task status is stored in a secondary workflow in the chain of the item).

![taskbar-viewlet](https://cloud.githubusercontent.com/assets/737356/8309202/5d9abac6-1986-11e5-96a0-36e1c50fdffa.png)
## Unknown/optional:
- Reminder overlay / icon may be future feature; unsure if we need to be able to select a recipient when multiple parties assigned.
- Should it be possible to hide/dismiss this viewlet temporarily, if distracting?
- Timezone: should this display in timezone of viewer or assigned party?  In either case, the mock is not explicit but text may need to be.  The catch is that abbreviated names for timezones (e.g. MDT vs Olson-style America/Denver) are not in pytz's vocabularies (though US/Mountain is, which is the form we tend to use with events).

**Comment by seanupton** [comment]
@aclark4life this is not an item for this week AFAICT, but this viewlet mock displays the way task status might be displayed on an item that is secondarily a task and primarily something else (calendar event, form).

**Comment by garbas** [comment]
we allow to assign task also to groups. should we somehow make this visible in the UI?
eg:

```
Assigned: Rok, Alex, ...
Assigned Teams: DevOps, ... 
```

should we also show project_manager? like we do assigned?

**Comment by aclark4life** [comment]
@garbas I'm all for showing more at first and removing later if need be.

**Comment by aclark4life** [comment]
Done in 463f2f2fe02f87aff9423e4131e324ce5f239c16
