### ISSUE TITLE
Identify content type icons

### ISSUE THREAD

**Issue by seanupton** [upiq/uu.task#2]
Identify content type icons for:
- Task planner (ordered container of tasks)
- Task
## Requirements
- Minimal effort.
- Use something already existing under a free/OSS license?
- Can re-use icons from Plone for Task Planner, if necessary (e.g. book_icon.png).
- My sense of iconographic language for task is a checkbox metaphor, preferably monochromatic.
- I would prefer not to, but can create something in Inkscape if I need to.

While content that is secondarily using task behavior will have its own icons, we want to have these two icons for types (at least for Plone 4.3**) for the OOTB content types.

> **Side-note: Plone 5 seems to eschew content type icons in toolbar menus; the one strategy for eventually supporting both icons in 4.3 and no-icons in 5.0+ is using CSS to provide the icon instead of the icon property of the FTI.

**Comment by aclark4life** [comment]
These may be close enough:
- Planner: https://github.com/iconic/open-iconic/blob/master/png/calendar.png
- Task: https://github.com/iconic/open-iconic/blob/master/png/task.png

As for icons vs. CSS I'd suggest including both then we can easily do whatever we like later. I think OpenIconic may include both options which is nice.

**Comment by seanupton** [comment]
I like this choice, looks good.  Let's just add the PNG versions to the FTIs, and put some note in the docs/ directory with credit/link for third-party-sourced assets.   Once those two things are done, we can close this.

**Comment by aclark4life** [comment]
Looks good
![screenshot 2015-06-17 05 55 11](https://cloud.githubusercontent.com/assets/72164/8204313/b3f9e3fe-14b5-11e5-8de6-962571c98ae2.png)
