### ISSUE TITLE
Create 4 catalog indexes

### ISSUE THREAD

**Issue by aclark4life** [upiq/uu.task#39]
- **Index/query requirement 1**: method gets all tasks not marked as not complete with notification date between (datetime1, datetime2) (inclusive)... method performing query could return catalog brains or actual content objects in list
- **index/query requirement 2**: "overdue tasks" method queries all tasks not marked as complete, with due date before (datetime1)
- **index requirement 3**: "my tasks or tasks for a specific party specified" -- query for all tasks, sorted in chronological order, that belong to an assigned principal (by user name), optionally excluding (or limiting to) tasks already marked as complete.  Use case: page lists user's tasks broken down by "completed", "pending", "overdue"  (it may be that sorting results into these categories need not necessarily perform 3 queries)
- **index requirement 4**: "tasks that I assigned to other people" -- similar to above, but for tasks assigned by named project manager (by username) to others. 
  In all these indexes, presumed path index used
  If data structure other than portal_catalog used for (some/all) indexing, assume that some "join" on the catalog results (for at least path index), filtering the non-catalog results by set-union of content UUIDs

These four query scenarios, AFAICT, take care of 90% or more of use cases for special views or portlets we may create in future, and most of the requirements of notification daemon (other than the storage of whether a notification is sent)

**Comment by garbas** [comment]
**Index/query requirement 1**

A range for unknown number of indexes is not possible in the catalog. i have to re-imagine the problem a bit differently. This requirement is probably meant for the notifications daemon which will have daily or nightly triggers.

daily query:

```
  now = datetime.now()
  catalog({
    "portal_type": "uu.task",
    "task_state": ["created", "discarded", "inprogress"],
    "task_notifications_day": int(time.mkdtime(datetime(
      now.year, now.month, now.day
    ))),
  })
```

hourly query:

```
  now = datetime.now()
  catalog({
    "portal_type": "uu.task",
    "task_state": ["created", "discarded", "inprogress"],
    "task_notifications_hour": int(time.mkdtime(datetime(
      now.year, now.month, now.day, now.hour
    ))),
  })
```

**index/query requirement 2**

"overdue tasks" method queries all tasks not marked as complete, with due date before (datetime1)

```
  now = datetime.now()
  catalog({
    "portal_type": "uu.task",
    "task_state": ["created", "discarded", "inprogress"],
    "task_due": {"query": DateTime(), "range": "min"}, 
  })
```

**index requirement 3**

```
  now = datetime.now()
  catalog({
    "portal_type": "uu.task",
    "task_state": ["created", "discarded", "inprogress"],
    "task_assignee": ["userid1"], 
  })
```

**index requirement 4**

```
  now = datetime.now()
  catalog({
    "portal_type": "uu.task",
    "task_state": ["created", "discarded", "inprogress"],
    "task_project_manager": ["userid1"], 
  })
```

**Comment by aclark4life** [comment]
Nice, thanks
